config/routes.rb
Rails.application.routes.draw do

  devise_for :admins,  controllers: { sessions: 'admins/sessions', registrations: 'admins/registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'admins#index'

  resources :admins do 
    resources :roles
    member do
      get :approve
    end
  end


  resources :chainly_configs

  resources :users do
    member do
      patch :gen_code
      patch :enable_code
      patch :disable_code
    end
  end
 
  resources :kycs do
    member do
      patch :accept
      patch :reject
    end
  end

  resources :contracts

  namespace :api do
    mount API::V1::Base => '/'
  end

  mount GrapeSwaggerRails::Engine => '/swagger'


end

app/models/kyc.rb
class Kyc < ApplicationRecord

  belongs_to :user
  
  belongs_to :front_img, class_name: "Image"
  belongs_to :back_img, class_name: "Image"

  include AASM
  aasm column: 'state' do
    state :verifing, initial: true
    state :accepted
    state :rejected

    event :accept do
      transitions from: :verifing, to: :accepted 
    end
    event :reject do
      transitions from: :verifing, to: :rejected
    end
 
  end

  def state_desc
    case self.state
    when 'verifing'
      '待验证'
    when 'accepted'
      '验证通过'
    when 'rejected'
      '驳回'
    else
      '未知'
    end
  end


end

app/controllers/kycs_controller.rb
# -*- encoding : utf-8 -*-
# == Schema Information
#
# Table name: admins
#
#  id                     :integer          not null, primary key
#  email                  :string(128)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null #  reset_password_token   :string(128)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  confirmation_token     :string(128)
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string(255) #  failed_attempts        :integer          default(0), not null
#  unlock_token           :string(128)
#  locked_at              :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  approved               :boolean          default(FALSE), not null
#

class KycsController < ApplicationController
  before_action :authorize_ability

  def authorize_ability
    authorize! :manage, Kyc
  end


  def index
    session['func'] = params[:func]
    session['func_index'] = params[:func_index]
    if(session['func_index'] == '1')
      @kycs = Kyc.where(state: 'verifing').order(updated_at: :desc).paginate page: params[:page], per_page: 10
    else
      @kycs = Kyc.all.order(updated_at: :desc).paginate page: params[:page], per_page: 10
    end
  end

  def accept
		kyc = Kyc.find(params[:id])
		kyc.accept!
    redirect_to kycs_path, notice: '审核完成！'
	end

  def reject
		kyc = Kyc.find(params[:id])
		kyc.reject!
    redirect_to kycs_path, notice: '已驳回！'
	end



end

app/views/kycs/_form.html.haml
= form_for @room, as: :room, url: @url do |f|
  .card-body
    .form-group
      %label{for: "price_addr"} 选择竞猜币种
      = f.select :price_addr, Coin.all.collect{|p|[p.name, p.addr]}, class: 'form-control', data: { behavior: 'select2' }, include_blank: "币种"

    .form-group
      %label{for: "join_coin_addr"} 选择投注币种
      = f.select :join_coin_addr, Coin.all.collect{|p|[p.name, p.addr]}, class: 'form-control', data: { behavior: 'select2' }, include_blank: "币种"
 
    .form-group
      %label{for: "time_level"} 每轮游戏开放投注时长(x分钟) 
      = f.text_field(:time_level, class: 'form-control', "placeholder": "输入分钟数")
    .form-group
      %label{for: "interval_minute"} 投注结束后开奖间隔时长(x分钟)，之后系统将自动开始结算
      = f.text_field(:interval_minute, class: 'form-control', "placeholder": "输入分钟数")
    .form-group
      %label{for: "invent_level"} 投注额度（投注当前币种的金额）
      = f.text_field(:invent_level, class: 'form-control', "placeholder": "投注额度")
    .form-group
      %label{for: "player_number"} 玩家人数上限数量
      = f.text_field(:player_number, class: 'form-control', "placeholder": "输入数量")
    .form-group
      %label{for: "winer_number"} 获胜玩家数量
      = f.text_field(:winer_number, class: 'form-control', "placeholder": "输入数量")
    .form-group
      %label{for: "rate"} 费率x%
      = f.text_field(:rate, class: 'form-control', "placeholder": "输入费率")



  .card-footer
    %button.btn.btn-primary{type: "submit"} 提交
    %button.btn.btn-default{type: "reset"} 重置

app/views/kycs/index.html.haml
%section.content-header
  .container-fluid
    .row.mb-2
      .col-sm-6
        %h1 审核列表
      .col-sm-6 
        %ol.breadcrumb.float-sm-right
          %li.breadcrumb-item 审核管理
          %li.breadcrumb-item.active 信息列表

%section.content
  .card
    .p-0
      %table.table.table-bordered
        %tbody
          %tr
            %th ID
            %th 用户ID
            %th 真实姓名
            %th 身份证号
            %th 正面
            %th 背面
            %th 审核状态
            %th 上传时间
            %th 操作
          - @kycs.each do |kyc|
            %tr
              %td 
                = kyc.id
              %td
                = kyc.user_id
              %td
                = kyc.name
              %td{style: "text-overflow = ellipsis;max-width: 150px;overflow: hidden;white-space: nowrap;resize: horizontal;"}
                = kyc.id_no
              %td{style: "text-overflow = ellipsis;max-width: 250px;overflow: hidden;white-space: nowrap;resize: horizontal;"}
                = brac_image(kyc.front_img.try(:file), version: :thumb)
              %td{style: "text-overflow = ellipsis;max-width: 250px;overflow: hidden;white-space: nowrap;resize: horizontal;"}
                = brac_image(kyc.back_img.try(:file), version: :thumb)
              %td 
                = kyc.state_desc
              %td 
                = brac_datetime(kyc.created_at)
              %td 
                - if kyc.verifing?
                  = link_to(raw('<i class="fas fa-user-check">&nbsp;</i>'), accept_kyc_path(kyc), data: { confirm: '确定审核通过吗?'}, method: :patch)
                  = link_to(raw('<i class="fas fa-times-circle">&nbsp;</i>'), reject_kyc_path(kyc), data: { confirm: '确定拒绝该审核吗?'}, method: :patch)

    .card-footer.clearfix
      %ul.pagination.pagination-sm.m-0.float-right
        = will_paginate @kycs, :container => false

app/views/kycs/new.html.haml
%section.content-header
  .container-fluid
    .row.mb-2
      .col-sm-6
        %h1 添加房间
      .col-sm-6 
        %ol.breadcrumb.float-sm-right
          %li.breadcrumb-item 房间管理
          %li.breadcrumb-item.active 添加

%section.content
  .card.card-primary
    = render :partial => "form"