config/routes.rb
Rails.application.routes.draw do

  devise_for :admins,  controllers: { sessions: 'admins/sessions', registrations: 'admins/registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'admins#index'

  resources :admins do 
    resources :roles
    member do
      get :approve
    end
  end


  resources :chainly_configs

  resources :users do
    member do
      patch :gen_code
      patch :enable_code
      patch :disable_code
    end
  end
 
  resources :kycs do
    member do
      patch :accept
      patch :reject
    end
  end

  resources :contracts

  namespace :api do
    mount API::V1::Base => '/'
  end

  mount GrapeSwaggerRails::Engine => '/swagger'


end

app/models/role.rb
# == Schema Information
#
# Table name: roles
#
#  id            :bigint           not null, primary key
#  name          :string(32)
#  resource_type :string(255)
#  resource_id   :bigint
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Role < ApplicationRecord
  has_and_belongs_to_many :admins, :join_table => :admins_roles


  belongs_to :resource,
           :polymorphic => true,
           :optional => true


  validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

  scopify

  validates_inclusion_of :name, in: ['admin', 'operator']

  def self.role_text role
    case role
    when 'admin'
      '管理员'
    when 'operator'
      '运营人员'
    else
      '未知'
    end
  end


end

app/controllers/roles_controller.rb
# -*- encoding : utf-8 -*-
# == Schema Information
#
# Table name: admins
#
#  id                     :integer          not null, primary key
#  email                  :string(128)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(128)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  confirmation_token     :string(128)
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string(255)
#  failed_attempts        :integer          default(0), not null
#  unlock_token           :string(128)
#  locked_at              :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  approved               :boolean          default(FALSE), not null
#

class RolesController < ApplicationController

  before_action :authorize_ability

  def authorize_ability
    authorize! :manage, Role
  end


  def index
    @admin = Admin.find(params[:admin_id])
    @roles = @admin.roles
  end

  def new
    @admin = Admin.find(params[:admin_id])
    @role = Role.new
  end

  def create
    @admin = Admin.find(params[:admin_id])
    real_params = role_params
    if @admin.add_role(real_params[:name].to_sym)
      redirect_to admin_roles_path(@admin), notice: '创建成功！'
    else
      render action: 'new', alert: '创建失败！'
      redirect_back(fallback_location: new_admin_role_path(admin_id: @admin.id), alert: '创建失败')
    end
  end
 
  def destroy
    @admin = Admin.find(params[:admin_id])
    role = Role.find(params[:id])
    @admin.roles.delete(role)
    @roles = @admin.roles
    redirect_back(fallback_location: admin_roles_path(@admin), alert: '删除成功')
  end

  protected
  def role_params
    params.require(:role).permit!
  end

end

app/views/roles/_form.html.haml
= form_for [@admin, @role] do |f|
  .card-body
    .form-group 
      %label{for: "name"} 角色名称
      = f.select(:name, options_for_select([ [Role.role_text('admin'), 'admin'], [Role.role_text('operator'), 'operator']], ''), data: { behavior: 'daterangepicker' }, class: 'form-control')
  .card-footer
    %button.btn.btn-primary{type: "submit"} 提交
    %button.btn.btn-default{type: "reset"} 重置

app/views/roles/index.html.haml
%section.content-header
  .container-fluid
    .row.mb-2
      .col-sm-6
        %h1 权限管理
      .col-sm-6 
        %ol.breadcrumb.float-sm-right
          %li.breadcrumb-item 系统用户管理 
          %li.breadcrumb-item.active 权限管理

%section.content
  .card
    .card-header
      %h3.card-title 
        = "#{current_admin.email} 权限列表"
      .card-tools
        = link_to(raw('<button type="button" class="btn btn-block btn-primary">添加权限</button>'), new_admin_role_path(@admin.id))

    .card-body.table-responsive.p-0
      %table.table.table-bordered
        %tbody
          %tr
            %th 权限名称
            %th 资源类型
            %th 资源ID
            %th 操作
          - @roles.each do |role|
            %tr
              %td
                = Role.role_text(role.name)
              %td
                = role.resource_type
              %td
                = role.resource_id
              %td
                = link_to(raw('<i class="fa fa-trash">&nbsp;</i>'), admin_role_path(@admin, role), data: { confirm: '确定要删除该权限吗?'}, method: :delete )

    .box-footer.clearfix

app/views/roles/new.html.erb
<section class="content-header">
  <h1>权限管理<small>创建权限</small></h1>
</section>

<section class="content">
  <%= render :partial => "form" %>
</section>