config/routes.rb
Rails.application.routes.draw do

  devise_for :admins,  controllers: { sessions: 'admins/sessions', registrations: 'admins/registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'admins#index'

  resources :admins do 
    resources :roles
    member do
      get :approve
    end
  end


  resources :chainly_configs

  resources :users do
    member do
      patch :gen_code
      patch :enable_code
      patch :disable_code
    end
  end
 
  resources :kycs do
    member do
      patch :accept
      patch :reject
    end
  end

  resources :contracts

  namespace :api do
    mount API::V1::Base => '/'
  end

  mount GrapeSwaggerRails::Engine => '/swagger'


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--
This is a starter template page. Use this page to start your new project from
scratch. This page gets rid of all links and provides the needed markup only.
-->
<html lang="en">
<head> <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title>链租管理系统</title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
 
</head>
<body class="hold-transition sidebar-mini">
<div class="wrapper">

  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light border-bottom">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
      </li>
      <li class="nav-item d-none d-sm-inline-block">
        <a href="index3.html" class="nav-link">主面板</a>
      </li>
    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
      <div class="input-group input-group-sm">
        <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
        <div class="input-group-append">
          <button class="btn btn-navbar" type="submit">
            <i class="fas fa-search"></i>
          </button>
        </div>
      </div>
    </form>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
     <!-- Notifications Dropdown Menu -->
      <li class="nav-item dropdown">
        <a class="nav-link" data-toggle="dropdown" href="#">
          <i class="far fa-bell"></i>
          <span class="badge badge-warning navbar-badge">15</span>
        </a>
        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
          <span class="dropdown-header">15 Notifications</span>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-envelope mr-2"></i> 4 new messages
            <span class="float-right text-muted text-sm">3 mins</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-users mr-2"></i> 8 friend requests
            <span class="float-right text-muted text-sm">12 hours</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item">
            <i class="fas fa-file mr-2"></i> 3 new reports
            <span class="float-right text-muted text-sm">2 days</span>
          </a>
          <div class="dropdown-divider"></div>
          <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#"><i
            class="fas fa-th-large"></i></a>
      </li>
    </ul>
  </nav>
  <!-- /.navbar -->

  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <div class="brand-link">
      <%= image_pack_tag("logo.png", class: "brand-image img-circle elevation-3", style: "opacity: .8")%>
      <span class="brand-text font-weight-light">链租管理</span>
    </div>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <%= image_pack_tag("avatar.png", class: "img-circle elevation-2")%>"
        </div>
        <div class="info">
          <%= link_to("退出系统", destroy_admin_session_path, data: { confirm: '确定要退出吗?'}, method: :delete ) %>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
          <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
                    <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->

          <li class="nav-item has-treeview <%= "menu-open" if session['func'] == 'kycs' %>">
            <a href="#" class="nav-link <%= "active" if 'kycs' == session['func'] %>">
              <i class="nav-icon fas fa-coins"></i>
              <p>
                审核管理
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="<%=kycs_path(func: 'kycs', func_index: '1')%>" class="nav-link <%= "active" if 'kycs' == session['func'] and '1' == session['func_index'] %>">
                  <i class="fas fa-list nav-icon"></i>
                  <p>待审核认证</p>
                </a>
              </li>
              <li class="nav-item">
                <a href="<%=kycs_path(func: 'kycs', func_index: '2')%>" class="nav-link <%= "active" if 'kycs' == session['func'] and '2' == session['func_index'] %>">
                  <i class="fas fa-list nav-icon"></i>
                  <p>全部审核认证</p>
                </a>
              </li>
           </ul>
          </li>

          <li class="nav-item has-treeview <%= "menu-open" if session['func'] == 'promoter' %>">
            <a href="#" class="nav-link <%= "active" if 'promoter' == session['func'] %>">
              <i class="nav-icon fas fa-coins"></i>
              <p>
                用户管理
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="<%=users_path(func: 'promoter', func_index: '1')%>" class="nav-link <%= "active" if 'promoter' == session['func'] and '1' == session['func_index'] %>">
                  <i class="fas fa-list nav-icon"></i>
                  <p>用户列表</p>
                </a>
              </li>
           </ul>
          </li>

          <li class="nav-item has-treeview <%= "menu-open" if session['func'] == 'contract' %>">
            <a href="#" class="nav-link <%= "active" if 'contract' == session['func'] %>">
              <i class="nav-icon fas fa-coins"></i>
              <p>
                合同管理
                <i class="right fas fa-angle-left"></i>
              </p>
            </a>
            <ul class="nav nav-treeview">
              <li class="nav-item">
                <a href="<%=contracts_path(func: 'contracts', func_index: '1')%>" class="nav-link <%= "active" if 'contract' == session['func'] and '1' == session['func_index'] %>">
                  <i class="fas fa-list nav-icon"></i>
                  <p>合同列表</p>
                </a>
              </li>
           </ul>
          </li>



          <% if current_admin.has_role? 'admin' %>
            <li class="nav-item">
              <a href="<%=edit_chainly_config_path(id: ChainlyConfig.first.try(:id) || 0, func: 'chainly_config')%>" class="nav-link <%= "active" if 'chainly_config' == session['func'] %>">
                <i class="nav-icon fas fa-tools"></i>
                <p>
                  设置链上费率
                  <span class="right badge badge-danger">管理员</span>
                </p>
              </a>
            </li>
 
            <li class="nav-item">
              <a href="<%=admins_path(func: 'system', func_index: '1')%>" class="nav-link <%= "active" if 'system' == session['func'] %>">
                <i class="nav-icon fas fa-users"></i>
                <p>
                  系统用户管理
                  <span class="right badge badge-danger">管理员</span>
                </p>
              </a>
            </li>
          <% end %>

        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
    <%= brac_flash %>
    <%= yield %>
  </div>
  <!-- /.content-wrapper -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
      Anything?
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2019-2020 <a href="https://www.rent.com">Rent</a>.</strong> All rights reserved.
  </footer>
</div>
<!-- ./wrapper -->

<!-- REQUIRED SCRIPTS -->

</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  <title>链租管理系统</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <!--[if lt IE 9]>
  <script src="http://cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="http://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>
<body class="hold-transition login-page">
  <%= brac_flash %>
  <div class="login-box">
    <h2>链租管理系统</h2>
    <%= yield %>
  </div>
</body>
</html>